apply plugin: 'com.android.application'

// count tags and use as Android versionCode
// https://developer.android.com/studio/publish/versioning
def getVersionCode = { ->
    def stream = providers.exec {
        commandLine 'git', 'rev-list', '--count', 'master'
    }.standardOutput
    return stream.asText.get().split("\n").size() as Integer
}

def getVersionDate = { ->
    def stream = providers.exec {
        commandLine 'git', 'log', '-1', '--format=%as'
    }.standardOutput
    return stream.asText.get().trim().replace('-','.') //.replaceAll("[^\\x00-\\x7F]", "")
}

def getVersionCommit = { ->
    def stream = providers.exec {
        commandLine 'git', 'log', '-1', '--format=%h'
    }.standardOutput
    return stream.asText.get().trim() //.replaceAll("[^\\x00-\\x7F]", "")
}

android {
    def app_name = "Sa2ration"
    def app_version = getVersionDate()
    def app_commit = getVersionCommit()

    compileSdk {
        version = release(37) {
            // this block and its properties are optional
            minorApiLevel = 1
            //sdkExtension = 18
        }
        //version = preview("CinnamonBun")
    }
    defaultConfig {
        applicationId = "com.github.edeso.sa2ration"
        namespace = 'com.xda.sa2ration'
        minSdk = 21
        targetSdk = 37
        versionCode = getVersionCode()
        versionName = "${app_version}-${app_commit}"
        base.archivesName = "${app_name}-${app_version}-${app_commit}"
        resValue "string",
                "app_commit",
                groovy.json.StringEscapeUtils.escapeJavaScript("${app_commit}")

    }
    buildFeatures {
        resValues = true
        buildConfig = true
    }
    buildTypes {
        debug {
            applicationIdSuffix = '.debug'
            versionNameSuffix = '-DEBUG'
            resValue "string",
                    "app_name",
                    groovy.json.StringEscapeUtils.escapeJavaScript("${app_name} Debug ${app_version}")
        }
        release {
            resValue "string",
                    "app_name",
                    groovy.json.StringEscapeUtils.escapeJavaScript("${app_name} ${app_version}")
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        targetCompatibility = 1.11
        sourceCompatibility = 1.11
    }
    viewBinding {
        enabled = true
    }
}

dependencies {
    //implementation fileTree(dir: 'libs', include: ['*.jar'])
    // appcompat v1.7+ API21
    implementation 'androidx.appcompat:appcompat:1.7.1'
    // material v1.14+ API23
    //noinspection GradleDependency,NewerVersionAvailable
    //implementation 'com.google.android.material:material:1.13.0'

    // workaround fix 'Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules ...'
    //implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.0.0"))
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ["-Xlint:deprecation"]
}

// new AGP9 DSL variant to rename release apk only
androidComponents {
    onVariants(selector().all()) { variant ->
        if (variant.buildType.equals("release")) {
            variant.outputs.forEach { output ->
                output.outputFileName.set("${base.archivesName.get()}.apk")
            }
        }
    }
}